In [2]:
# Importing the needed lib
from sklearn import datasets
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [27]:
# Loading the Iris datat
iris = datasets.load_iris()

# Taking out the labels and the features
X = iris.data
y = iris.target

classes = X.shape, y.shape, iris.target_names

In [22]:
# Spliting the data into the training and testing data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120, 1)
(30, 1)


In [54]:
# from sklearn import svm
# from sklearn.metrics import accuracy_score
# model = svm.SVC()
# model.fit(X_train, y_train)

# prediction = model.predict(X_test)
# acc = accuracy_score(y_test, prediction)
# print(acc)

# from sklearn.linear_model import LinearRegression
# from sklearn.metrics import accuracy_score
# model = LinearRegression()
# model.fit(X_train, y_train)

# prediction = model.predict(X_test)
# acc = accuracy_score(y_test, prediction)
# print(acc)
# This didnt work because this case is a classification problem and the machine learning algorithm cannot comprehend the incoming data and process it linearly



In [68]:
# Now trying out anthor classification method which is the Logistic Regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

acc = accuracy_score(y_test, y_pred)
print(acc)

# Most accurate

C:\Users\DAVID\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


1.0


In [72]:
# Now trying out anthor classification method which is the Decision Tree
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)

# Predicting a new result
prediction = regressor.predict(X_test)

acc = accuracy_score(y_test, prediction)
print(acc)

# another most correct

1.0


In [75]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, y_train)

prediction = regressor.predict(X_test)

acc = accuracy_score(y_test, prediction)
print(acc)
#  This didnt work because random forest is a is not that great for classification

<ipython-input-75-b6d5dfb319d1>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor.fit(X_train, y_train)


ValueError: Classification metrics can't handle a mix of multiclass and continuous targets

In [77]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

acc = accuracy_score(y_test, y_pred)
print(acc)

[[15  0  0]
 [ 0  9  0]
 [ 0  0  6]]
1.0


C:\Users\DAVID\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [79]:
# Training the K-NN model on the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

acc = accuracy_score(y_test, y_pred)
print(acc)

[[15  0  0]
 [ 0  9  0]
 [ 0  0  6]]
1.0


<ipython-input-79-058c9094af6f>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  classifier.fit(X_train, y_train)
