In [1]:
# Importing the needed Lib
import numpy as np

In [5]:
# IMporting My wine dataset
from sklearn.datasets import load_wine


In [10]:
ds = load_wine()

X = ds['data']
y = ds['target']

y_label_in_string = ds['target_names']
X_label_in_string = ds['feature_names']

In [11]:
# Preprocessing the data (Most thing have been done since thid is a clean data i would just be spliting the data into trainging and testing data)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=50)

In [12]:
# Feature Scaling (I wa think there was no need for scaling the data but it turns out that without scaling the data, the algorithm would get to it max iteration even before the the learningprocess is done here by causing waste of computation)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
# Traing the model (Since this is a bin classification i would prefer using the logistic regresson, by the way this is athe best in cases like this)
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 50)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=50)

In [14]:
# prediction and socring the LogReg model
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(y_test)
print(y_pred)
print(cm)

[1 1 1 2 2 2 1 1 0 2 0 0 1 0 1 2 1 2 1 0 0 1 0 2 0 0 1 1 0 1 0 0 2 2 0 1]
[1 1 1 2 2 2 1 1 0 2 0 0 1 0 1 2 1 2 1 0 0 1 0 2 0 0 1 1 0 1 0 0 2 2 0 1]
[[13  0  0]
 [ 0 14  0]
 [ 0  0  9]]
